FCT_homepage:
    path:     /
    defaults: { _controller: LandingBundle:Default:index }
FCT_empresa_new:
    path:     /empresa/new
    defaults: { _controller: FCTBundle:Empresa:new }
FCT_empresa_all:
    path:     /empresa/all
    defaults: { _controller: FCTBundle:Empresa:all }
FCT_alumno_all: 
    path:     /alumno/all
    defaults: { _controller: FCTBundle:Alumno:all }
FCT_empresas_POST:
    path:     /api/empresas
    defaults: { _controller: FCTBundle:Api:post }
    methods: [POST]
FCT_empresas_GET:
    path:     /api/empresas
    defaults: { _controller: FCTBundle:Api:get }
    methods: [GET]

